### ISSUE TITLE
Incorrect tooltip on mobile

### ISSUE THREAD

**Issue by SebinSong** [okTurtles/group-income-simulator#3]
### 1. Problem

![image](https://github.com/okTurtles/group-income-simulator/assets/17641213/8f941485-8a12-424c-b3b4-4c8eb854fe34)

(Confirmed this happens in the version of `main` branch before mergence of the PR #2)

On mobile device, the tooltip that is spawned upon clicking on the user banner UI component incorrectly says who they are.
This issue is only happening in mobile and caused by how the app currently detects user-click.
Normally, `click` or `touchdown` event is used but the app currently tracks the pointer only using `mousemove` handler in the canvas area, which is an incomplete logic for any touch devices.

### 2. Solution
Improve the logic that detects user-click so it's applicable to both desktop / touch-devices and fix the issue.

**Comment by taoeffect** [comment]
Nice catch! Also, in that screenshot for some reason the buttons at the bottom are poorly arranged across two rows instead of one 🤔

**Comment by SebinSong** [comment]
@taoeffect That is a screenshot of the previous version of `main` before my recent PR #2 . So no worries.
